export SAMPLE_COMPARTMENT_OCID=ocid1.tenancy.oc1..aaaaaaaagckwvz7s7xhdpentvxr3xdcu22mlbjehnpjfpf5h26fhwnrsdryq
export SAMPLE_AD_NAME=zStx:SA-SAOPAULO-1-AD-1
export SAMPLE_INSTANCE_SHAPE=VM.Standard.E2.1.Micro
export SAMPLE_IMAGE_OCID=ocid1.image.oc1.sa-saopaulo-1.aaaaaaaa3ibxbkfvmcdyshvkuzhpc2wx2ofmpjyyjf5tyh3eqge7vc7d5rtq